# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c24575edd25da4e7f29b108472ef9ba398daca776de51743413565d009f5724c147dc46fb0f51996a3022a047674aa23e8ddc2b880e41622b979355c6be3ebf

test:
  secret_key_base: 42ad82804e129886b638b0dfe28b4433adb57728c3e25898c6b88c583200c2011ad5ee7b63f9896bb529ae1f543e45a49cf6ad50bccdb56831834362718edcb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
